web:
  port: 8080

database:
  driverName: postgres
  dataSourceName: diggpher
  host: localhost
  port: 5432
  user: postgres
  psw: 123456
  timeZone: Asia/Shanghai

redis:
  addr: localhost:6379
  password: ""

logger:
  level: info
  console: true
  dir: ./logs
